version: 0.2

env:
  variables:
    BACKEND_REPOSITORY_NAME: "pulseplus-backend"
    FRONTEND_REPOSITORY_NAME: "pulseplus-frontend"

phases:
  install:
    runtime-versions:
      nodejs: 18
      docker: 20
    commands:
      - npm install -g npm@latest
      - npm install -g aws-cli
      - curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - BACKEND_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BACKEND_REPOSITORY_NAME
      - FRONTEND_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$FRONTEND_REPOSITORY_NAME
      - echo "BACKEND_REPOSITORY_URI: $BACKEND_REPOSITORY_URI"
      - echo "FRONTEND_REPOSITORY_URI: $FRONTEND_REPOSITORY_URI"
      - sed -i 's|${BACKEND_IMAGE}|'"${BACKEND_REPOSITORY_URI}:${IMAGE_TAG}"'|g' docker-compose.yml
      - sed -i 's|${FRONTEND_IMAGE}|'"${FRONTEND_REPOSITORY_URI}:${IMAGE_TAG}"'|g' docker-compose.yml

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker-compose build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $BACKEND_REPOSITORY_URI:$IMAGE_TAG
      - docker push $FRONTEND_REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"backend","imageUri":"%s"},{"name":"frontend","imageUri":"%s"}]' $BACKEND_REPOSITORY_URI:$IMAGE_TAG $FRONTEND_REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json