version: 0.2

env:
  variables:
    NODE_ENV: "test"
  parameter-store:
    SNYK_TOKEN: "/pulseplus/ci/snyk_token"
    AWS_ACCOUNT_ID: "/pulseplus/ci/aws_account_id"
  secrets-manager:
    JWT_SECRET: "pulseplus/jwt:secret"
    DB_PASSWORD: "pulseplus/db:password"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g snyk
      # Install OWASP ZAP
      - echo Installing OWASP ZAP...
      - wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz
      - tar -xf ZAP_2.12.0_Linux.tar.gz
      - rm ZAP_2.12.0_Linux.tar.gz
      - mv ZAP_2.12.0 /opt/zap
      - export PATH=$PATH:/opt/zap
      # Install SonarQube Scanner
      - echo Installing SonarQube Scanner...
      - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip -q sonar-scanner-cli-4.7.0.2747-linux.zip
      - mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin

  pre_build:
    commands:
      - echo Running security scans...
      - export SECURITY_SCANNING_ENABLED=true
      - node scripts/security-scan.js --all
      - echo Running linting...
      - npm run lint
      - echo Running tests...
      - npm test

  build:
    commands:
      - echo Building the application...
      - npm run build
      - echo Running integration tests...
      - npm run test:integration

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging application...
      - npm prune --production
      - aws cloudformation package --template-file template.yml --s3-bucket $S3_BUCKET --s3-prefix $S3_PREFIX --output-template-file packaged.yml

artifacts:
  files:
    - packaged.yml
    - appspec.yml
    - scripts/**/*
    - backend/**/*
    - frontend/build/**/*
    - node_modules/**/*
    - package.json
    - reports/**/*
  discard-paths: no

reports:
  security-reports:
    files:
      - "reports/snyk-results.json"
      - "reports/zap-results.json"
      - "reports/sonarqube-results.json"
    file-format: "JSON"
  test-reports:
    files:
      - "reports/jest-*.xml"
    file-format: "JUNITXML"

cache:
  paths:
    - 'node_modules/**/*'
    - '/root/.npm/**/*' 