services:
  frontend:
    image: ${FRONTEND_IMAGE}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:3001"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_URL=${POSTGRES_URL}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=pulseplus-admin
      - POSTGRES_PASSWORD=Work4PulsePlus1
      - POSTGRES_DB=pulseplus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: