services:
  frontend:
    container_name: pulseplus-frontend
    image: ${FRONTEND_IMAGE}
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
        - NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
      - NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend

  backend:
    container_name: pulseplus-backend
    image: ${BACKEND_IMAGE}
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - JWT_SECRET=${JWT_SECRET}
        - SESSION_SECRET=${SESSION_SECRET}
        - NODE_ENV=${NODE_ENV}
        - POSTGRES_URL=${POSTGRES_URL}
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - REBUILD_DB=${REBUILD_DB}
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:3001"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_URL=${POSTGRES_URL}
      - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - REBUILD_DB=${REBUILD_DB}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: pulseplus-db
    image: postgres:13
    environment:
      - POSTGRES_USER=pulseplus-admin
      - POSTGRES_PASSWORD=Work4PulsePlus1
      - POSTGRES_DB=pulseplus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: