version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: 
      - .env.${NODE_ENV:-development}
    # ... other configurations

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env.${NODE_ENV:-development}
    # ... other configurations