apiVersion: v1
kind: ConfigMap
metadata:
  name: pulseplus-config
data:
  LOG_LEVEL: "info"
  ENABLE_STRUCTURED_LOGGING: "true"
  ENABLE_REQUEST_LOGGING: "true"
  MAX_LOG_FILE_SIZE: "10m"
  MAX_LOG_RETENTION_DAYS: "7"
  CORS_ALLOWED_ORIGINS: "https://pulseplus.example.com"
  API_RATE_LIMIT: "100"
  API_RATE_LIMIT_WINDOW_MS: "60000" 