apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulseplus-postgres-pvc
  labels:
    app: pulseplus
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 