apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulseplus-redis-pvc
  labels:
    app: pulseplus
    tier: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard 