apiVersion: v1
kind: Secret
metadata:
  name: pulseplus-secrets
type: Opaque
stringData:
  # Database credentials
  postgres-url: "postgresql://username:password@pulseplus-postgres:5432/pulseplus"
  postgres-user: "pulseplus-admin"
  postgres-password: "change-me-in-production"
  
  # Authentication secrets
  jwt-secret: "your-jwt-secret-here"
  session-secret: "your-session-secret-here"
  
  # Redis credentials
  redis-password: "your-redis-password-here"
  
  # SMTP configuration
  smtp-host: "smtp.example.com"
  smtp-port: "587"
  smtp-user: "smtp-user"
  smtp-password: "smtp-password"
  smtp-from: "no-reply@example.com"

# Note: This is a template file. Do not commit actual secrets to version control.
# Replace placeholder values with actual secrets before applying to your cluster.
# Consider using a secrets management solution like Vault or Sealed Secrets. 